### ISSUE TITLE
Resolve sibling folders with babel?

### ISSUE THREAD

**Issue by nealoke** [josephluck/next-plugin-custom-babel-config#4]
Hi! First of all great plugin 👍  Just have an issue when I try to resolve aliases in a sibling, any idea on how I could tackle the issue?

https://stackoverflow.com/questions/58059091/unable-to-resolve-alias-in-sibling-folder-using-for-nextjs-project

**Comment by josephluck** [comment]
Hey @nealoke - do you have an example repo set up that I could take a look at? Difficult to understand your project set up without seeing some source code.

I know you're using lerna, but I set up an example project using yarn workspaces: https://github.com/josephluck/next-typescript-monorepo that might provide you some insight? There's also an accompanying blog post explaining the set up here: https://josephluck.co.uk/blog/next-typescript-monorepo/

Hope this helps!

**Comment by nealoke** [comment]
Thanks for the answer but aperently it has a specific issue with `react-native-web-maps` so the question I posted is not entirely correct. So 2 days of searching for something that was not the issue 😓
