### ISSUE TITLE
No longer works with next.js 11

### ISSUE THREAD

**Issue by fabb** [josephluck/next-plugin-custom-babel-config#8]
Does not work anymore with next.js 11 because the loader is no longer called `'next-babel-loader'` but `'/absolute/path/to/project/node_modules/next/dist/build/babel/loader/index.js'`.

I guess this is related to next.js 11 having inlined the babel loader and others: https://github.com/vercel/next.js/pull/20598

**Comment by JCMais** [comment]
@fabb did you find a fix or alternative?

**Comment by fabb** [comment]
I removed the plugin and duplicated the babel config for every application.

**Comment by josephluck** [comment]
Hey folks. I'm no longer maintaining this plugin, but PRs are most welcome!

**Comment by fabb** [comment]
@josephluck what do you use yourself instead?

maybe you could add a hint to the readme that next.js 11 is no longer supported?

**Comment by josephluck** [comment]
I'm no longer actively working with NextJS.

> maybe you could add a hint to the readme that next.js 11 is no longer supported?

Good shout!

**Comment by hippotastic** [comment]
I've fixed the issue, added tests and created a PR. Hope that helps.

**Comment by josephluck** [comment]
@rutzfutz - thank you!

Published @1.0.5 https://www.npmjs.com/package/next-plugin-custom-babel-config

**Comment by JCMais** [comment]
Thanks @rutzfutz!

**Comment by hippotastic** [comment]
Most welcome! My thanks go to @fabb for analyzing the change that caused this bug.

**Comment by hippotastic** [comment]
By the way, @josephluck - the NPM package description for 1.0.5 still states "This plugin doesn't work with Next 11. PRs welcome!", which isn't true anymore.
